version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtualenv'
          command: |
            uv venv --python 3.12 /usr/local/share/virtualenvs/singer-encodings
            source /usr/local/share/virtualenvs/singer-encodings/bin/activate
            uv pip install .[dev]
      - run:
          name: 'Unit tests'
          command: |
            source /usr/local/share/virtualenvs/singer-encodings/bin/activate
            uv pip install .[dev]
            pytest tests

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
